#ifndef __DEFINE__H
#define __DEFINE__H

#define NETWORK_ERROR_START_FAILED			0x01
#define NETWORK_ERROR_SOCKET_FAILED			NETWORK_ERROR_START_FAILED + 1
#define NETWORK_ERROR_NETBUFFER_OVER		NETWORK_ERROR_SOCKET_FAILED + 1

#endif
