#ifndef __ERROR__H
#define __ERROR__H

#define NET_ERROR_LISTEN_FAILED			10000
#define NET_ERROR_INITIAL_FAILED		NET_ERROR_LISTEN_FAILED + 1
#define NET_ERROR_SOCKET_FAILED			NET_ERROR_INITIAL_FAILED + 1
#define NET_ERROR_NETBUFFER_OVER		NET_ERROR_SOCKET_FAILED + 1
#define NET_ERROR_SESSION_TIMEOUT		NET_ERROR_NETBUFFER_OVER + 1

#define NET_FATAL_INVALID_SIZE			20000

#endif
